from pyspark.sql import SparkSession, functions as f
from pyspark.sql.types import StructType,StructField,StringType,MapType,ArrayType,LongType,DateType,BooleanType, DoubleType 

spark = SparkSession.builder.appName("Silver Schemas").getOrCreate()

volumeSchema = StructType([
        StructField("kind",StringType(),False),
        StructField("id",StringType(),False),
        StructField("etag",StringType(),False),
        StructField("selfLink",StringType(),False),
        StructField("volumeInfo",StructType([
            StructField("title",StringType(),False),
            StructField("subtitle",StringType(),True),
            StructField("authors",ArrayType(StringType()),False),
            StructField("publisher",StringType(),True),
            StructField("publisherDate",StringType(),True),
            StructField("description",StringType(),True),
            StructField("industryIdentifiers",ArrayType(StructType([
                StructField("type",StringType(),True),
                StructField("identifier",StringType(),True)
            ])),True),
            StructField("pageCount",LongType(),True),
            StructField("dimensions",StructType([
                StructField("height",StringType(),True),
                StructField("width",StringType(),True),
                StructField("thickness",StringType(),True)
            ]),True),
            StructField("printType",StringType(),True),
            StructField("mainCategory",StringType(),True),
            StructField("categories",ArrayType(StringType()),True),
            StructField("averageRating",LongType(),True),
            StructField("ratingsCount",LongType(),True),
            StructField("contentVersion",StringType(),True),
            StructField("imageLinks",StructType([
                StructField("smallThumbnail",StringType(),True),
                StructField("thumbnail",StringType(),True),
                StructField("small",StringType(),True),
                StructField("medium",StringType(),True),
                StructField("large",StringType(),True),
                StructField("extraLarge",StringType(),True),
            ]),True),
            StructField("language",StringType(),True),
            StructField("previewLink",StringType(),True),
            StructField("infoLink",StringType(),True),
            StructField("canonicalVolumeLink",StringType(),True),
        ])),
        StructField("saleInfo",StructType([
            StructField("country",StringType(),True),
            StructField("saleability",StringType(),True),
            StructField("onSaleDate",DateType(),True),
            StructField("isEbook",BooleanType(),True),
            StructField("listPrice",StructType([
                StructField("amount",DoubleType(),True),
                StructField("currencyCode",StringType(),True),
            ]),True),
            StructField("retailPrice",StructType([
                StructField("amount",DoubleType(),True),
                StructField("currencyCode",StringType(),True),
            ]),True),
            StructField("buyLink",StringType(),True)
        ]),True),
        StructField("accessInfo",StructType([
            StructField("country",StringType(),True),
            StructField("viewability",StringType(),True),
            StructField("embeddable",BooleanType(),True),
            StructField("publicDomain",BooleanType(),True),
            StructField("textToSpeechPermission",StringType(),True),
            StructField("epub",StructType([
                StructField("isAvailable",BooleanType(),True),
                StructField("downloadLink",StringType(),True),
                StructField("acsTokenLink",StringType(),True)
            ]),True),
            StructField("pdf",StructType([
                StructField("isAvailable",BooleanType(),True),
                StructField("downloadLink",StringType(),True),
                StructField("acsTokenLink",StringType(),True)
            ]),True),
            StructField("webReaderLink",StringType(),True),
            StructField("accessViewStatus",StringType(),True),
            StructField("downloadAccess",StructType([
                StructField("kind",StringType(),True),
                StructField("volumeId",StringType(),True),
                StructField("restricted",BooleanType(),True),
                StructField("deviceAllowed",BooleanType(),True),
                StructField("justAcquired",BooleanType(),True),
                StructField("maxDownloadDevices",LongType(),True),
                StructField("downloadsAcquired",LongType(),True),
                StructField("nonce",StringType(),True),
                StructField("source",StringType(),True),
                StructField("reasonCode",StringType(),True),
                StructField("message",StringType(),True),
                StructField("signature",StringType(),True),
            ]),True),
        ]),True),
        StructField("searchInfo",StructType([
            StructField("textSnippet",StringType(),True)
        ]),True)
    ])

googleSchema = StructType([
        StructField("isbn",StringType(),False),
        StructField("kind",StringType(),False),
        StructField("totalItems",LongType(),False),
        StructField("items",ArrayType(volumeSchema),False)
    ])
